
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/practice?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: nextlevel
        password: nextlevel

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
    port: 8081