babu: from application.yml
spring:
  application:
    name: continuous
  datasource:
    url: jdbc:mysql://localhost:3306/continuous?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: nextlevel
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8081
